#!/bin/bash

set -eu

function buyPrompt {
    prompt="\nGo to buy tickets? (y/n) " 
    echo -e -n "$prompt" 
    read buy_ticket

    while [[ "$buy_ticket" != "y" && "$buy_ticket" != "n" ]] ; do
        echo "That was not a valid answer."
        echo -e -n "$prompt"
        read buy_ticket
    done

    if [[ "$buy_ticket" == "y" ]] ; then
        open `cat buyTicketUrl.txt`
    else
        exit 0
    fi
}

pushd `dirname "$0"` > /dev/null
SCRIPT_PATH=`pwd -P`
CONCERTS_PATH="$SCRIPT_PATH/concerts"

# remove old listings
rm -rf concerts/*

casperjs "$SCRIPT_PATH/tso.js"

doPrompt=$?

if [[ $doPrompt -eq 0 ]] ; then                                                    
    cd "$CONCERTS_PATH"
    concert_count_spaces="$(find ./*/ -type d -print | wc -l)"
    concert_count="${concert_count_spaces//[[:space:]]}"

    for c in $(find . ! -name . -type d) ; do
        cd "$CONCERTS_PATH"
        cd $c
        terminal-notifier -message "$(cat performances.txt)" \
            -title "$(cat title.txt)" -open "$(cat buyUrl.txt)" \
            -sound default
        sleep 5
    done
else                                                                        
    exit 1
fi  

