#!/bin/bash

set -eu

function buyPrompt {
    prompt="\nGo to buy tickets? (y/n) " 
    echo -e -n "$prompt" 
    read buy_ticket

    while [[ "$buy_ticket" != "y" && "$buy_ticket" != "n" ]] ; do
        echo "That was not a valid answer."
        echo -e -n "$prompt"
        read buy_ticket
    done

    if [[ "$buy_ticket" == "y" ]] ; then
        open `cat buyTicketUrl.txt`
    else
        exit 0
    fi
}

pushd `dirname "$0"` > /dev/null
SCRIPT_PATH=`pwd -P`

casperjs "$SCRIPT_PATH/tso.js"

doPrompt=$?

if [[ $doPrompt -eq 0 ]] ; then                                                    
    terminal-notifier -message "$(cat concert/details.txt)" \
        -title "$(cat concert/title.txt)" -open "$(cat concert/buyUrl.txt)"
else                                                                        
    exit 1
fi  

